objects = reverse_temperature_conversion.o

reverse_temperature_conversion : $(objects)
	gcc -o reverse_temperature_conversion.out $(objects)

$(objects) : 

.PHONY : clean
clean :
	rm reverse_temperature_conversion $(objects)

